org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.238
neo_version_range=[21.1.238,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=xenopixelsmod
mod_name=XenoPixels Network
mod_license=All Rights Reserved
mod_version=0.1.6-1.21.1
mod_group_id=net.bullettrain.xenopixelsmod
mod_authors=bullettrain
mod_description=XenoPixels Network - custom DMZ server content, Xenoverse-style HUD, combat, missiles, and Sable ship integration for DragonMineZ.

geckolib_version=4.9.2
terrablender_version=1.21.1-4.1.0.8
curios_version=9.5.1+1.21.1
sable_project_id=T9PomCSv
sable_version_id=1L6XJqnY
sable_companion_version=1.6.0
cc_tweaked_version=1.120.0
xaerolib_version=1.1.0
xaero_world_map_version=1.40.16
