package net.bullettrain.xenopixelsmod.client.dmz;

import net.bullettrain.xenopixelsmod.XenoPixelsMod;
import net.minecraft.client.Minecraft;
import net.minecraft.resources.ResourceLocation;

import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Per-form radial icons shipped with the mod, for forms of the bundled groups that should not all
 * share their group's icon (Super Saiyan Blue 3 and Rose 3, generated by
 * {@code tools/gen_god_form_icons.py}). A form has one when
 * {@code assets/xenopixelsmod/textures/gui/radial/<group>_<form>.png} exists; Form Studio metadata
 * is asked first and wins.
 */
public final class BundledFormIcons {
    private static final Map<String, Optional<ResourceLocation>> CACHE = new ConcurrentHashMap<>();

    private BundledFormIcons() {
    }

    /** The texture path such an icon would have, whether or not it exists; null for an unusable id. */
    public static ResourceLocation path(String group, String form) {
        if (group == null || form == null || group.isBlank() || form.isBlank()) return null;
        return ResourceLocation.tryBuild(XenoPixelsMod.MOD_ID,
                "textures/gui/radial/" + group.toLowerCase(java.util.Locale.ROOT) + "_"
                        + form.toLowerCase(java.util.Locale.ROOT) + ".png");
    }

    /** The shipped icon of this form, or null when it has none. */
    public static ResourceLocation radial(String group, String form) {
        ResourceLocation candidate = path(group, form);
        if (candidate == null) return null;
        return CACHE.computeIfAbsent(candidate.getPath(), key ->
                Minecraft.getInstance().getResourceManager().getResource(candidate).isPresent()
                        ? Optional.of(candidate) : Optional.empty()).orElse(null);
    }
}
