package net.bullettrain.xenopixelsmod.fx.effek;

import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.*;

/** Every effect slot ships an .efkefc whose referenced textures, materials and models exist. */
class EffectAssetsTest {
    static final Path EFFEKS = Path.of(System.getProperty("xenopixels.projectDir"),
            "src/main/resources/assets/xenopixelsmod/effeks");
    static final String[] SLOTS = {"punch_impact", "punch_heavy", "punch_guard", "hakai_channel",
            "hakai_crumble", "hakai_erase", "hakai_palm", "missile_explosion", "missile_thruster",
            "ship_thruster", "sparking_aura", "sparking_aura_smooth", "sparking_burst", "sparking_flight"};

    /** Relative asset paths stored in the file (Effekseer writes them as UTF-16LE strings). */
    static List<String> references(Path efk) throws Exception {
        byte[] bytes = Files.readAllBytes(efk);
        List<String> out = new ArrayList<>();
        // Effects store paths as UTF-16LE (at either byte alignment); materials store them as ASCII.
        List<String> texts = new ArrayList<>();
        texts.add(new String(bytes, StandardCharsets.ISO_8859_1));
        for (int shift = 0; shift < 2; shift++) {
            texts.add(new String(bytes, shift, bytes.length - shift, StandardCharsets.UTF_16LE));
        }
        for (String text : texts) {
            Matcher m = Pattern.compile("[\\w./ -]+\\.(?:png|dds|tga|efkmat|efkmodel)", Pattern.CASE_INSENSITIVE)
                    .matcher(text);
            while (m.find()) out.add(m.group().trim());
        }
        return out;
    }

    @Test
    void everySlotHasItsEffectAndEveryReferencedFile() throws Exception {
        for (String slot : SLOTS) {
            Path efk = EFFEKS.resolve(slot).resolve(slot + ".efkefc");
            assertTrue(Files.isRegularFile(efk), "missing " + efk);
            for (String ref : references(efk)) {
                assertTrue(Files.isRegularFile(efk.getParent().resolve(ref)), slot + " references missing " + ref);
            }
        }
    }

    /**
     * 2026-09-28 in game: every effect but the thruster failed with "Invalid segment 'Parts' in
     * path 'effeks/punch_guard/Parts/Aura.png'". Minecraft resource paths are lower-case only, so
     * every file under effeks/ and every path an effect or material references must be valid.
     */
    @Test
    void everyFileAndReferenceIsAValidMinecraftResourcePath() throws Exception {
        try (var files = Files.walk(EFFEKS)) {
            for (Path file : files.filter(Files::isRegularFile).toList()) {
                String rel = "effeks/" + EFFEKS.relativize(file).toString().replace('\\', '/');
                assertTrue(validPackPath(rel), "invalid resource path " + rel);
                String name = file.getFileName().toString();
                if (name.endsWith(".efkefc") || name.endsWith(".efkmat")) {
                    for (String ref : references(file)) {
                        String refPath = "effeks/" + EFFEKS.relativize(file.getParent().resolve(ref).normalize())
                                .toString().replace('\\', '/');
                        assertTrue(validPackPath(refPath),
                                name + " references invalid resource path " + refPath);
                        assertTrue(Files.isRegularFile(file.getParent().resolve(ref)),
                                name + " references missing " + refPath);
                    }
                }
            }
        }
    }

    /**
     * Vanilla's pack path rule, checked directly: AAA Particles patches ResourceLocation.isValidPath
     * to accept upper case, but the pack loader still rejects it.
     */
    static boolean validPackPath(String path) {
        return path.matches("[a-z0-9/._-]+");
    }

    @Test
    void theStandInsAreCreditedAsCcZero() throws Exception {
        String credits = Files.readString(EFFEKS.resolve("credits.txt"));
        assertTrue(credits.contains("CC-0") && credits.contains("Effekseer"));
    }

    @Test
    void everyEffectSlotHasItsFile() {
        for (EffectSlot slot : EffectSlot.values()) {
            assertTrue(Files.isRegularFile(EFFEKS.resolve(slot.path() + ".efkefc")), "missing " + slot);
        }
    }

    /**
     * 2026-09-28 owner: the Hakai stand-ins looked odd; the Hakai effects are now generated by
     * tools/effekseer/gen_hakai_effects.py and use only its own purple textures.
     */
    @Test
    void theHakaiEffectsAreTheGeneratedOnes() throws Exception {
        Path tools = Path.of(System.getProperty("xenopixels.projectDir"), "tools/effekseer/hakai");
        for (String slot : new String[] {"hakai_channel", "hakai_crumble", "hakai_erase", "hakai_palm"}) {
            Path efk = EFFEKS.resolve(slot).resolve(slot + ".efkefc");
            List<String> refs = references(efk);
            assertFalse(refs.isEmpty(), slot);
            for (String ref : refs) {
                assertTrue(ref.matches("texture/hakai_[a-z]+[.]png"), slot + " uses " + ref);
            }
            assertTrue(Files.isRegularFile(tools.resolve(slot).resolve(slot + ".efkproj")),
                    slot + " keeps its editable source");
        }
    }

    /**
     * 2026-10-03 owner: HD aura v3 (silhouette + punch edges + form-coloured sparking) is generated
     * by {@code python tools/effekseer/gen_effects.py aura3} into {@code effeks/aura3/}.
     */
    @Test
    void aura3EffectsAreTheGeneratedOnes() throws Exception {
        Path folder = EFFEKS.resolve("aura3");
        assertTrue(Files.isDirectory(folder), "missing aura3 folder");
        assertTrue(Files.isDirectory(folder.resolve("texture")), "missing aura3/texture");
        try (var files = Files.list(folder)) {
            long count = files.filter(p -> p.getFileName().toString().endsWith(".efkefc")).count();
            assertEquals(1080, count, "90 colours x 6 brightness x depth/_nz");
        }
        Path sample = folder.resolve("aura3_ffd700.efkefc");
        assertTrue(Files.isRegularFile(sample), "missing sample " + sample);
        List<String> refs = references(sample);
        assertFalse(refs.isEmpty(), "aura3_ffd700");
        for (String ref : refs) {
            assertTrue(ref.matches("texture/aura3_[a-z0-9_]+[.]png"), "aura3 uses " + ref);
            assertTrue(Files.isRegularFile(folder.resolve(ref)), "missing " + ref);
        }
        assertTrue(Files.isRegularFile(Path.of(System.getProperty("xenopixels.projectDir"),
                "tools/effekseer/aura3/aura3_ffd700.efkproj")), "editable aura3 source");
    }

    /**
     * 2026-09-29 owner: "i dont see a new thurster animations ... also new sparking effect not
     * showing". The plumes and Sparking are generated by tools/effekseer/gen_effects.py.
     */
    @Test
    void thrusterAndSparkingEffectsAreTheGeneratedOnes() throws Exception {
        Path tools = Path.of(System.getProperty("xenopixels.projectDir"), "tools/effekseer");
        String[][] sets = {{"thruster", "missile_thruster", "plume_"}, {"thruster", "ship_thruster", "plume_"},
                {"sparking", "sparking_aura", "spark_"}, {"sparking", "sparking_burst", "spark_"},
                {"sparking", "sparking_flight", "spark_"}};
        for (String[] set : sets) {
            Path efk = EFFEKS.resolve(set[1]).resolve(set[1] + ".efkefc");
            List<String> refs = references(efk);
            assertFalse(refs.isEmpty(), set[1]);
            for (String ref : refs) {
                assertTrue(ref.matches("texture/" + set[2] + "[a-z_]+[.]png"), set[1] + " uses " + ref);
            }
            assertTrue(Files.isRegularFile(tools.resolve(set[0]).resolve(set[1]).resolve(set[1] + ".efkproj")),
                    set[1] + " keeps its editable source");
        }
    }

    /** 2026-09-29 owner: the explosion like tools/new_particles/on_explostion_of_missile_particle_iwant.png. */
    @Test
    void theExplosionIsTheGeneratedOne() throws Exception {
        Path efk = EFFEKS.resolve("missile_explosion/missile_explosion.efkefc");
        List<String> refs = references(efk);
        assertFalse(refs.isEmpty());
        for (String ref : refs) assertTrue(ref.matches("texture/blast_[a-z_]+[.]png"), "uses " + ref);
        assertTrue(Files.isRegularFile(Path.of(System.getProperty("xenopixels.projectDir"),
                "tools/effekseer/explosion/missile_explosion/missile_explosion.efkproj")));
    }
}
