package net.bullettrain.xenopixelsmod.client;

import com.dragonminez.client.util.KeyBinds;
import com.dragonminez.common.stats.StatsCapability;
import com.dragonminez.common.stats.StatsData;
import com.dragonminez.common.stats.StatsProvider;
import com.dragonminez.common.stats.character.Cooldowns;
import com.dragonminez.common.stats.character.Status;
import com.dragonminez.common.stats.techniques.TechniqueData;
import com.dragonminez.common.stats.techniques.Techniques;
import net.bullettrain.xenopixelsmod.XenoPixelsMod;
import net.bullettrain.xenopixelsmod.client.config.XenoClientConfig;
import net.bullettrain.xenopixelsmod.client.config.XenoHotbarConfig;
import net.bullettrain.xenopixelsmod.client.config.XenoHudConfig;
import net.bullettrain.xenopixelsmod.client.hud.AnimUtil;
import net.bullettrain.xenopixelsmod.client.hud.TechniqueSlotWidget;
import net.minecraft.client.KeyMapping;
import net.minecraft.client.Minecraft;
import net.minecraft.client.DeltaTracker;
import net.minecraft.client.gui.Font;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.player.LocalPlayer;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.Style;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.api.distmarker.OnlyIn;
import net.neoforged.neoforge.client.settings.KeyModifier;
import com.dragonminez.compat.util.LazyOptional;

import java.util.Locale;
import java.util.Map;

/**
 * XenoPixels KI technique hotbar — inherits equipped slots live from DMZ
 * {@link Techniques#getEquippedSlots()} (same source as TechniqueHotbarHUD).
 */
@OnlyIn(Dist.CLIENT)
public class XenoTechniqueHotbarOverlay {
    /** DMZ uses 8 technique slots (Alt 0-3, Ctrl 4-7). */
    private static final int TOTAL_SLOTS = 8;
    private static final int BAR_SLOTS = 4;
    private static final int SLOT_H = 18;
    private static final int SLOT_GAP = 3;
    private static final int PANEL_PAD = 6;
    private static final int BADGE_W = 14;
    private static final int MARGIN = 10;

    /** Xenoverse blank menu panel. Generated by {@code scripts/import_hud_elements.py}. */
    private static final ResourceLocation MENU_PANEL = ResourceLocation.fromNamespaceAndPath(
            XenoPixelsMod.MOD_ID, "textures/gui/xenoverse/combat/ki_menu_panel.png");
    private static final int MENU_TEX_W = 512;
    private static final int MENU_TEX_H = 334;

    /**
     * The selected-row glow, as a separate texture.
     *
     * <p>The panel artwork used to bake its highlight into row 3, so the bar always looked like
     * slot 3 was live no matter which slot the player had selected. This is the same chrome as a
     * standalone element so it can be placed on whichever row is actually selected.
     *
     * <p>The panel artwork used to bake its highlight into row 3, so the bar always looked like
     * slot 3 was live no matter which slot the player had selected. This is the same chrome cut
     * out as a standalone bar so it can be placed on whichever row is actually selected.
     */
    private static final ResourceLocation MENU_HIGHLIGHT = ResourceLocation.fromNamespaceAndPath(
            XenoPixelsMod.MOD_ID, "textures/gui/xenoverse/combat/ki_menu_row_highlight.png");
    private static final int HL_TEX_W = 512;
    private static final int HL_TEX_H = 71;

    /**
     * Where the artwork already drew its wells, as fractions of the panel.
     *
     * <p>The four rows are <b>baked into the texture</b>, so unlike the combat buttons this panel
     * cannot be sliced to arbitrary proportions — it is drawn at its own aspect and the content is
     * placed on top of the rows that already exist. Measured off the source by
     * {@code scripts/import_hud_elements.py}; do not hand-tune these.
     */
    private static final float MENU_ASPECT = 1.534f;
    private static final float[] ROW_CENTRE = {0.3441f, 0.5103f, 0.6728f, 0.8374f};
    private static final float HEADER_CENTRE = 0.150f;
    private static final float KEY_L = 0.1277f, KEY_R = 0.2079f;
    private static final float NAME_L = 0.2146f, NAME_R = 0.8215f;
    private static final float STATUS_L = 0.8290f, STATUS_R = 0.8636f;

    /**
     * Where the highlight bar has to land to sit on a row's chrome, in panel fractions.
     *
     * <p>It is a standalone element rather than a slice of the panel canvas, so it is fitted to the
     * row rather than blitted at panel coordinates. Its own glow falloff is inside the crop, which
     * is why the fitted height is wider than the row band itself.
     */
    private static final float HL_L = 0.048f, HL_R = 0.912f;
    private static final float HL_H = 0.175f;

    /** Name tint by slot state. Shared so the textured and procedural paths cannot disagree. */
    private static int nameColorFor(boolean empty, boolean known, boolean onCd, boolean charging,
                                    boolean selected) {
        if (empty) return 0xFF556677;
        if (!known) return 0xFFFFCC80;
        if (onCd) return 0xFFFF8A80;
        if (charging) return 0xFFFFE082;
        // The selected row sits on bright blue chrome, which the configured name tint (a pale blue)
        // washes out against. Full white is the one that still reads there.
        if (selected) return 0xFFFFFFFF;
        return XenoHotbarConfig.partColor(XenoHotbarConfig.Part.NAME);
    }

    private static Component styled(String text, int part) {
        return Component.literal(text).setStyle(Style.EMPTY
                .withFont(XenoHotbarConfig.partFontLocation(part))
                .withBold(XenoHotbarConfig.partBold[part]));
    }

    private static float partWidth(Font font, int part, String text) {
        if (text == null || text.isEmpty()) return 0f;
        return font.width(styled(text, part)) * XenoHotbarConfig.partScale(part);
    }

    /** One menu element, with its own colour, scale, weight and the shared HUD font. */
    private static void drawPart(GuiGraphics g, Font font, int part, String text,
                                 float x, float y, int colorOverride) {
        if (text == null || text.isEmpty()) return;
        float scale = XenoHotbarConfig.partScale(part);
        int color = colorOverride != 0 ? colorOverride : XenoHotbarConfig.partColor(part);
        g.pose().pushPose();
        g.pose().translate(x + XenoHotbarConfig.defaultPartDx(part) + XenoHotbarConfig.partX(part),
                y + XenoHotbarConfig.defaultPartDy(part) + XenoHotbarConfig.partY(part), 0);
        g.pose().scale(scale, scale, 1f);
        g.drawString(font, styled(text, part), 0, 0, color, false);
        g.pose().popPose();
    }

    /** Same cooldown key prefix DMZ TechniqueHotbarHUD / ClientStatsEvents use: {@code TechniqueCooldown_} + id */
    private static final String CD_PREFIX = "TechniqueCooldown_";

    private static final int[] CD_LAST_TICKS = new int[TOTAL_SLOTS];
    private static final long[] CD_LAST_MS = new long[TOTAL_SLOTS];
    private static final String[] CD_LAST_ID = new String[TOTAL_SLOTS];

    /** Slot chrome helper (vanilla fills only — safe without LDLib). */
    private static final TechniqueSlotWidget SLOT_WIDGET = new TechniqueSlotWidget();

    /** Screen-space bounds of the last drawn panel/charge-meter — captured each frame so the
     *  editor screen can hit-test them without re-deriving the (data-dependent) panel size. */
    private static int lastHotbarX, lastHotbarY, lastHotbarW, lastHotbarH;
    private static int lastChargeX, lastChargeY, lastChargeW, lastChargeH;
    private static boolean lastChargeVisible;

    public void render(GuiGraphics g, DeltaTracker deltaTracker) {
        if (!XenoClientConfig.techniqueHotbarEnabled) return;
        Minecraft mc = Minecraft.getInstance();
        if (mc.player == null || mc.options.hideGui || mc.getDebugOverlay().showDebugScreen()) return;
        // Chat / command prompt / any screen open: never show Alt/Ctrl tech bar
        if (XenoClientConfig.techniqueHotbarHideInChat && mc.screen != null) return;
        draw(g, g.guiWidth(), g.guiHeight(), false);
    }

    /** Renders a preview (forced-visible bar + a fake charging meter) for the editor screen. */
    public static void renderEditorPreview(GuiGraphics g, int screenWidth, int screenHeight) {
        draw(g, screenWidth, screenHeight, true);
    }

    public static int[] hotbarBounds() {
        return new int[]{lastHotbarX, lastHotbarY, lastHotbarW, lastHotbarH};
    }

    public static int[] chargeBounds() {
        return new int[]{lastChargeX, lastChargeY, lastChargeW, lastChargeH};
    }

    private static void draw(GuiGraphics g, int screenWidth, int screenHeight, boolean editing) {
        Minecraft mc = Minecraft.getInstance();
        if (mc.player == null) return;

        LocalPlayer player = mc.player;
        LazyOptional<StatsData> opt = StatsProvider.get(StatsCapability.INSTANCE, player);
        if (!opt.isPresent()) return;
        StatsData data = opt.orElse(null);
        if (data == null || !data.isDataLoaded()) return;

        Status status = data.getStatus();
        if (status == null || !status.isHasCreatedCharacter()) return;

        // Live DMZ technique state (equipped slots, charge, selection)
        Techniques techniques = data.getTechniques();
        if (techniques == null) return;

        String[] equipped = techniques.getEquippedSlots();
        if (equipped == null) equipped = new String[TOTAL_SLOTS];

        Map<String, TechniqueData> unlocked = techniques.getUnlockedTechniques();
        Cooldowns cds = data.getCooldowns();
        int selected = techniques.getSelectedSlot();
        String chargingId = techniques.getChargingTechniqueId();
        float chargePct = techniques.getTechniqueChargePercent();
        boolean charging = techniques.isTechniqueCharging() || techniques.isTechniqueChargeActive();

        lastChargeVisible = charging || editing;
        if (lastChargeVisible) {
            // techniqueChargePercent is percent points (0–200 stock, up to the configured cap).
            // In editor preview mode, fake a mid-charge value so the bar is visible to position.
            float previewPct = charging ? chargePct : 450f;
            String previewName = charging ? resolveName(unlocked, chargingId) : "Preview Technique";
            drawChargeMeter(g, mc.font, screenWidth, screenHeight, previewPct, previewName, editing);
        } else {
            lastChargeX = lastChargeY = lastChargeW = lastChargeH = 0;
        }

        KeyMapping[] keys = KeyBinds.TECHNIQUE_SLOTS;
        if (keys == null || keys.length < TOTAL_SLOTS) return;

        // Same Alt/Ctrl bar selection as DMZ TechniqueHotbarHUD
        KeyModifier modAlt = keys[0].getKeyModifier();
        KeyModifier modCtrl = keys[4].getKeyModifier();
        boolean altDown = KeyBinds.isBarModifierActive(modAlt);
        boolean ctrlDown = KeyBinds.isBarModifierActive(modCtrl);

        int offset;
        if (editing) {
            // Editor screens don't reliably see held modifier keys — always show the ALT bar
            // (or CTRL if actually held) so the panel can be positioned/resized.
            offset = ctrlDown ? 4 : 0;
        } else if (ctrlDown && modCtrl != modAlt) {
            offset = 4;
        } else if (altDown) {
            offset = 0;
        } else if (ctrlDown) {
            offset = 4;
        } else {
            lastHotbarX = lastHotbarY = lastHotbarW = lastHotbarH = 0;
            return;
        }

        Font font = mc.font;

        int maxNameW = 80;
        for (int i = 0; i < BAR_SLOTS; i++) {
            int idx = offset + i;
            String id = slotId(equipped, idx);
            TechniqueData td = resolveTechnique(unlocked, id);
            maxNameW = Math.max(maxNameW, font.width(displayName(td, id)));
        }

        boolean shell = XenoHotbarConfig.xenoverseShell;
        int innerW = BADGE_W + 6 + maxNameW + 44;
        int panelW = PANEL_PAD * 2 + innerW;
        int panelH = PANEL_PAD * 2 + BAR_SLOTS * SLOT_H + (BAR_SLOTS - 1) * SLOT_GAP;
        if (shell) {
            // The rows are baked in, so height follows the artwork rather than the content.
            panelW = Math.max(panelW, 190);
            panelH = Math.round(panelW / MENU_ASPECT);
        }

        int baseX = MARGIN + XenoHotbarConfig.hotbarOffsetX;
        int baseY = screenHeight - MARGIN - panelH - 22 + XenoHotbarConfig.hotbarOffsetY;
        float hScale = XenoHotbarConfig.hotbarScale;
        lastHotbarX = baseX;
        lastHotbarY = baseY;
        lastHotbarW = Math.round(panelW * hScale);
        lastHotbarH = Math.round(panelH * hScale);

        g.pose().pushPose();
        g.pose().translate(baseX, baseY, 0);
        g.pose().scale(hScale, hScale, 1f);
        int panelX = 0;
        int panelY = 0;

        String barLabel = offset == 0 ? "KI · ALT" : "KI · CTRL";
        if (shell) {
            g.blit(MENU_PANEL, panelX, panelY, panelW, panelH, 0f, 0f,
                    MENU_TEX_W, MENU_TEX_H, MENU_TEX_W, MENU_TEX_H);
            // Before any row content: the bar's glow bleeds a little past its row, and the rows are
            // drawn top-down, so highlighting from inside that loop would wash over the row above.
            int selRow = selected - offset;
            boolean selCharging = false;
            if (selRow >= 0 && selRow < BAR_SLOTS) {
                String selId = slotId(equipped, selected);
                selCharging = charging && !selId.isEmpty() && selId.equals(chargingId);
            } else if (editing) {
                // Nothing is selected while an editor screen has focus, and an element that is not
                // on screen cannot be dragged. Park it on the first row so it is always editable.
                selRow = 0;
            }
            if (selRow >= 0 && selRow < BAR_SLOTS) {
                drawRowHighlight(g, panelX, panelY, panelW, panelH, selRow, selCharging);
            }
            // The artwork has its own header band, so the label sits inside the panel rather than
            // floating above it the way the procedural plate needed.
            drawPart(g, font, XenoHotbarConfig.Part.HEADER, barLabel,
                    panelX + panelW * NAME_L,
                    panelY + panelH * HEADER_CENTRE - font.lineHeight * 0.5f, 0);
        } else {
            fillRounded(g, panelX - 2, panelY - 2, panelW + 4, panelH + 4, 0xCC050510);
            fillRounded(g, panelX, panelY, panelW, panelH, 0xEE0A1428);
            drawBox(g, panelX, panelY, 3, panelH, offset == 0 ? 0xFF42A5F5 : 0xFFFF7043);
            g.drawString(font, barLabel, panelX + PANEL_PAD + 4, panelY - 11, 0xFF90CAF9, true);
        }

        // Which slot is live, not how many are filled: a hotbar counter that never moves as you
        // switch reads as broken. getSelectedSlot() is 0-based and -1 when nothing is selected.
        String countLabel = (Math.max(0, selected) + 1) + "/" + TOTAL_SLOTS;
        if (shell) {
            drawPart(g, font, XenoHotbarConfig.Part.COUNT_LABEL, countLabel,
                    panelX + panelW * NAME_R - partWidth(font, XenoHotbarConfig.Part.COUNT_LABEL, countLabel),
                    panelY + panelH * HEADER_CENTRE - font.lineHeight * 0.5f, 0);
        } else {
            g.drawString(font, countLabel, panelX + panelW - font.width(countLabel) - 4,
                    panelY - 11, 0xFF78909C, false);
        }

        // DMZ refuses KI casts while holding an item — surface that while the bar is open
        if (!editing && !player.getMainHandItem().isEmpty()) {
            String warn = "Empty hand to cast";
            g.drawString(font, warn, panelX + PANEL_PAD + 4, panelY + panelH + 2, 0xFFFFB74D, true);
        }

        for (int i = 0; i < BAR_SLOTS; i++) {
            int idx = offset + i;
            int rowY = panelY + PANEL_PAD + i * (SLOT_H + SLOT_GAP);
            int rowX = panelX + PANEL_PAD;

            // Direct inheritance from DMZ equippedSlots[idx]
            String techId = slotId(equipped, idx);
            TechniqueData td = resolveTechnique(unlocked, techId);
            String name = displayName(td, techId);
            boolean empty = techId.isEmpty();
            boolean known = td != null;

            int cdTicks = 0;
            if (!empty && cds != null) {
                // Match DMZ TechniqueHotbarHUD cooldown key exactly
                cdTicks = cds.getCooldown(CD_PREFIX + techId);
                if (cdTicks <= 0) {
                    // fallbacks some builds used
                    cdTicks = Math.max(cdTicks, cds.getCooldown(techId));
                }
            }
            float cdSec = interpolateCd(idx, techId, cdTicks);
            boolean onCd = cdSec > 0.05f;
            boolean isSel = selected == idx;
            boolean isChargingThis = charging && !techId.isEmpty() && techId.equals(chargingId);

            int bg;
            if (isChargingThis) {
                bg = 0xCC4A2808;
            } else if (isSel) {
                bg = 0xCC1E4A7A;
            } else if (empty) {
                bg = 0x66101828;
            } else if (onCd) {
                bg = 0xAA3A1820;
            } else {
                bg = 0xAA122038;
            }
            float rowCentreY = panelY + panelH * ROW_CENTRE[i];
            if (shell) {
                // The plate is in the artwork; tint only the name band so its frame survives. The
                // selected row is skipped entirely -- its state is the highlight bar already drawn
                // under this loop, and a tint on top of that only mutes it.
                if (!isSel) {
                    int bandL = Math.round(panelX + panelW * NAME_L);
                    int bandR = Math.round(panelX + panelW * NAME_R);
                    int bandH = Math.max(6, Math.round(panelH * 0.105f));
                    int tint = (bg & 0x00FFFFFF) | 0x66000000;
                    g.fill(bandL, Math.round(rowCentreY - bandH / 2f), bandR,
                            Math.round(rowCentreY + bandH / 2f), tint);
                }
            } else {
                fillRounded(g, rowX, rowY, innerW, SLOT_H, bg);
            }

            int outline = shell ? 0 : (isChargingThis ? 0xFFFFB74D : (isSel ? 0xFF42A5F5 : 0));
            if (outline != 0) {
                if (isSel || isChargingThis) {
                    // Animated pulse for selected/charging slots — visual polish.
                    float pulse = AnimUtil.pulse01(isChargingThis ? 450L : 900L);
                    int glow = isChargingThis ? 0xFFFFE0B2 : 0xFF90CAF9;
                    outline = AnimUtil.lerpColor(outline, glow, pulse * 0.6f);
                }
                drawOutlineBox(g, rowX, rowY, innerW, SLOT_H, outline, 1);
            }

            // Key badge from DMZ KeyBinds.TECHNIQUE_SLOTS[idx]
            String keyLabel = keyLabel(keys, idx);
            if (shell) {
                // The badge box and its outline are already drawn in the artwork.
                float kw = partWidth(font, XenoHotbarConfig.Part.KEY, keyLabel);
                drawPart(g, font, XenoHotbarConfig.Part.KEY, keyLabel,
                        panelX + panelW * (KEY_L + KEY_R) / 2f - kw / 2f,
                        rowCentreY - font.lineHeight * 0.5f, 0);
                drawPart(g, font, XenoHotbarConfig.Part.SLOT, String.valueOf(idx + 1),
                        panelX + panelW * NAME_L + 2, rowCentreY - font.lineHeight * 0.5f, 0);

                float nameLeft = panelX + panelW * NAME_L + 12;
                float nameRight = panelX + panelW * NAME_R - 4;
                String shown = name;
                float avail = nameRight - nameLeft - (onCd ? 26 : 0);
                if (partWidth(font, XenoHotbarConfig.Part.NAME, shown) > avail) {
                    shown = font.plainSubstrByWidth(shown, Math.max(1,
                            Math.round(avail / Math.max(0.05f, XenoHotbarConfig.partScale(XenoHotbarConfig.Part.NAME)))));
                }
                drawPart(g, font, XenoHotbarConfig.Part.NAME, shown, nameLeft,
                        rowCentreY - font.lineHeight * 0.5f,
                        nameColorFor(empty, known, onCd, isChargingThis, isSel));

                if (onCd) {
                    String cdsTxt = String.format(Locale.US, "%.1fs", cdSec);
                    drawPart(g, font, XenoHotbarConfig.Part.COOLDOWN, cdsTxt,
                            nameRight - partWidth(font, XenoHotbarConfig.Part.COOLDOWN, cdsTxt),
                            rowCentreY - font.lineHeight * 0.5f, 0);
                }

                // Status light in the artwork's square: the state the plate used to carry.
                int dot = empty ? 0x00000000
                        : isChargingThis ? 0xFFFFB74D
                        : onCd ? 0xFFFF7043
                        : isSel ? 0xFF64B5F6
                        : XenoHotbarConfig.partColor(XenoHotbarConfig.Part.STATUS);
                if (dot != 0) {
                    // Grown about its own centre so the Size buttons do something here too -- this
                    // is a filled rect rather than text, so it does not go through drawPart.
                    int st = XenoHotbarConfig.Part.STATUS;
                    int scx = Math.round(panelX + panelW * (STATUS_L + STATUS_R) * 0.5f)
                            + XenoHotbarConfig.defaultPartDx(st) + XenoHotbarConfig.partX(st);
                    int sy = Math.round(rowCentreY)
                            + XenoHotbarConfig.defaultPartDy(st) + XenoHotbarConfig.partY(st);
                    int half = Math.max(1, Math.round(
                            panelW * (STATUS_R - STATUS_L) * 0.5f * XenoHotbarConfig.partScale(st)));
                    g.fill(scx - half, sy - half, scx + half, sy + half, dot);
                }
                continue;
            }
            int bx = rowX + 2;
            int by = rowY + (SLOT_H - 12) / 2;
            drawBadgeBox(g, bx, by, BADGE_W, 12);
            drawOutlineBox(g, bx, by, BADGE_W, 12, isSel ? 0xFF64B5F6 : 0x88666688, 1);
            int kw = font.width(keyLabel);
            g.drawString(font, keyLabel, bx + Math.max(0, (BADGE_W - kw) / 2), by + 2, 0xFFFFFFFF, false);

            // Slot index pip (DMZ slot number 1-8)
            String slotNum = String.valueOf(idx + 1);
            g.drawString(font, slotNum, bx + BADGE_W + 4, rowY + 5, 0xFF607D8B, false);

            int nameX = bx + BADGE_W + 14;
            int nameColor;
            if (empty) {
                nameColor = 0xFF556677;
            } else if (!known) {
                nameColor = 0xFFFFCC80; // equipped id present but data not resolved yet
            } else if (onCd) {
                nameColor = 0xFFFF8A80;
            } else if (isChargingThis) {
                nameColor = 0xFFFFE082;
            } else {
                nameColor = 0xFFE3F2FD;
            }
            g.drawString(font, name, nameX, rowY + 5, nameColor, false);

            if (onCd) {
                String cdsTxt = String.format(Locale.US, "%.1fs", cdSec);
                int cw = font.width(cdsTxt);
                g.drawString(font, cdsTxt, rowX + innerW - cw - 4, rowY + 5, 0xFFFFAB91, true);
            } else if (!empty && known) {
                g.fill(rowX + innerW - 8, rowY + SLOT_H / 2 - 2,
                        rowX + innerW - 4, rowY + SLOT_H / 2 + 2, 0xFF66BB6A);
            }
        }

        if (editing) {
            g.renderOutline(panelX - 4, panelY - 16, panelW + 8, panelH + 20, 0xFF42A5F5);
            g.fill(panelX + panelW - 10, panelY + panelH - 10, panelX + panelW, panelY + panelH, 0xFF42A5F5);
        }

        g.pose().popPose();
    }

    /**
     * Lays the selected-row glow over one row of the panel.
     *
     * @param row row index within the visible bar (0-3), not the DMZ slot index
     */
    private static void drawRowHighlight(GuiGraphics g, int panelX, int panelY,
                                         int panelW, int panelH, int row, boolean charging) {
        int part = XenoHotbarConfig.Part.HIGHLIGHT;
        float scale = XenoHotbarConfig.partScale(part);

        // Grown about its own centre, like the status square: a texture cannot go through drawPart,
        // and anchoring the resize at the left edge would walk the bar off the row.
        int w = Math.max(1, Math.round(panelW * (HL_R - HL_L) * scale));
        int h = Math.max(1, Math.round(panelH * HL_H * scale));
        int cx = Math.round(panelX + panelW * (HL_L + HL_R) * 0.5f)
                + XenoHotbarConfig.defaultPartDx(part) + XenoHotbarConfig.partX(part);
        int cy = Math.round(panelY + panelH * ROW_CENTRE[row])
                + XenoHotbarConfig.defaultPartDy(part) + XenoHotbarConfig.partY(part);

        // Breathe rather than blink: the bar is large and a hard on/off at this size is noise.
        float pulse = AnimUtil.pulse01(charging ? 450L : 900L);
        int tint = XenoHotbarConfig.partColor(part);
        float r = ((tint >> 16) & 0xFF) / 255f;
        float gr = ((tint >> 8) & 0xFF) / 255f;
        float b = (tint & 0xFF) / 255f;
        float alpha = ((tint >>> 24) & 0xFF) / 255f * (0.82f + 0.18f * pulse);
        if (charging) {
            // The artwork is blue; pulling the green and blue channels down warms it to the charging
            // orange the rest of the bar uses, without needing a second texture.
            gr *= 0.80f;
            b *= 0.42f;
        }
        g.setColor(r, gr, b, alpha);
        g.blit(MENU_HIGHLIGHT, cx - w / 2, cy - h / 2, w, h, 0f, 0f,
                HL_TEX_W, HL_TEX_H, HL_TEX_W, HL_TEX_H);
        g.setColor(1f, 1f, 1f, 1f);
    }

    /**
     * @param rawPercent DMZ {@code getTechniqueChargePercent()} — range 0..1000 (already in %).
     */
    private static void drawChargeMeter(GuiGraphics g, Font font, int sw, int sh, float rawPercent, String techName, boolean editing) {
        // Normalize: DMZ stores 0–200; the charge-cap mixin lets this reach the configured max
        // (default 1000). Values are already percent points, not 0–1.
        float pct = Math.max(0f, Math.min(1000f, rawPercent));
        // If a build ever sends 0-1, scale up
        if (pct > 0f && pct <= 1.0001f) {
            pct *= 100f;
        }

        boolean over = pct > 175f;
        // 0-175% fills the main bar; overcharge sits on top as a pulse strip
        float fill01 = Math.min(1f, pct / 175f);
        float over01 = over ? Math.min(1f, (pct - 175f) / 825f) : 0f;

        int barW = 182;
        int barH = 12;
        int baseX = (sw - barW) / 2 + XenoHotbarConfig.chargeOffsetX;
        // Just above the vanilla hotbar / item slots
        int baseY = sh - 66 + XenoHotbarConfig.chargeOffsetY;
        float cScale = XenoHotbarConfig.chargeScale;

        lastChargeX = baseX - Math.round(3 * cScale);
        lastChargeY = baseY - Math.round(15 * cScale);
        lastChargeW = Math.round((barW + 6) * cScale);
        lastChargeH = Math.round((barH + 18) * cScale);

        g.pose().pushPose();
        g.pose().translate(baseX, baseY, 0);
        g.pose().scale(cScale, cScale, 1f);
        int x = 0;
        int y = 0;

        int filled = Math.round(barW * fill01);

        g.fill(x - 3, y - 3, x + barW + 3, y + barH + 3, 0xDD050510);
        g.fill(x - 1, y - 1, x + barW + 1, y + barH + 1, 0xFF2A2A3A);
        g.fill(x, y, x + barW, y + barH, 0xFF12121C);

        if (filled > 0) {
            int c1 = over ? 0xFFE53935 : 0xFF1E88E5;
            int c2 = over ? 0xFFFF8A80 : 0xFF64B5F6;
            g.fill(x, y, x + filled, y + barH, c1);
            g.fill(x, y, x + filled, y + 3, c2);
            // leading edge
            if (filled < barW) {
                g.fill(x + filled - 2, y, x + filled, y + barH, c2);
            }
        }

        // Overcharge layer: left→right fill of a bright strip proportional to 175→1000
        if (over01 > 0f) {
            int overW = Math.max(2, Math.round(barW * over01));
            g.fill(x, y + barH - 3, x + overW, y + barH, 0xFFFF1744);
            g.fill(x, y, x + overW, y + 2, 0xAAFFFFFF);
        }

        // Tick marks at 50% / 100%
        int mid = x + barW / 2;
        g.fill(mid, y, mid + 1, y + barH, 0x44FFFFFF);
        if (over) {
            g.fill(x + barW - 1, y, x + barW, y + barH, 0x88FF5252);
        }

        String label = over
                ? String.format(Locale.US, "OVERCHARGE %.0f%%", pct)
                : String.format(Locale.US, "CHARGING %.0f%%", pct);
        if (techName != null && !techName.isEmpty() && !techName.startsWith("—")) {
            label = techName + "  ·  " + label;
        }
        int tw = font.width(label);
        g.drawString(font, label, x + (barW - tw) / 2, y - 12, over ? 0xFFFF8A80 : 0xFFB3E5FC, true);

        if (editing) {
            g.renderOutline(x - 3, y - 15, barW + 6, barH + 18, 0xFFFFB74D);
            g.fill(x + barW - 7, y + barH - 4, x + barW + 3, y + barH + 6, 0xFFFFB74D);
        }

        g.pose().popPose();
    }

    /** DMZ equippedSlots[i] — empty string means vacant. */
    private static String slotId(String[] equipped, int idx) {
        if (equipped == null || idx < 0 || idx >= equipped.length) return "";
        String s = equipped[idx];
        return s == null ? "" : s;
    }

    /**
     * Resolve TechniqueData the same way DMZ does: unlockedTechniques.get(equippedId).
     * Also tries suffix / case-insensitive match if the map key form differs slightly.
     */
    private static TechniqueData resolveTechnique(Map<String, TechniqueData> unlocked, String id) {
        if (id == null || id.isEmpty() || unlocked == null || unlocked.isEmpty()) return null;

        TechniqueData direct = unlocked.get(id);
        if (direct != null) return direct;

        // Some techniques store id with different casing / namespace
        for (Map.Entry<String, TechniqueData> e : unlocked.entrySet()) {
            if (e.getKey() == null) continue;
            if (e.getKey().equalsIgnoreCase(id)) return e.getValue();
            if (e.getKey().endsWith("." + id) || id.endsWith("." + e.getKey())) return e.getValue();
            TechniqueData td = e.getValue();
            if (td != null && id.equals(td.getId())) return td;
            if (td != null && id.equalsIgnoreCase(td.getName())) return td;
        }
        return null;
    }

    private static String resolveName(Map<String, TechniqueData> unlocked, String id) {
        return displayName(resolveTechnique(unlocked, id), id == null ? "" : id);
    }

    private static String displayName(TechniqueData td, String id) {
        if (td != null) {
            String n = td.getName();
            if (n != null && !n.isEmpty()) {
                if (n.contains(".")) {
                    String translated = Component.translatable(n).getString();
                    if (translated != null && !translated.equals(n)) return translated;
                    // try as-is literal if translation missing
                    int d = n.lastIndexOf('.');
                    return d >= 0 ? pretty(n.substring(d + 1)) : pretty(n);
                }
                return n;
            }
            String tid = td.getId();
            if (tid != null && !tid.isEmpty()) {
                String tr = Component.translatable(tid).getString();
                if (tr != null && !tr.equals(tid)) return tr;
            }
        }
        if (id == null || id.isEmpty()) return "— empty —";

        // Translate equipped id if it's a lang key
        if (id.contains(".")) {
            String tr = Component.translatable(id).getString();
            if (tr != null && !tr.equals(id)) return tr;
            int d = id.lastIndexOf('.');
            return pretty(id.substring(d + 1));
        }
        return pretty(id);
    }

    private static String pretty(String raw) {
        if (raw == null || raw.isEmpty()) return "— empty —";
        String s = raw.replace('_', ' ').trim();
        if (s.isEmpty()) return "— empty —";
        // Capitalize words
        StringBuilder sb = new StringBuilder(s.length());
        boolean cap = true;
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == ' ') {
                sb.append(c);
                cap = true;
            } else if (cap) {
                sb.append(Character.toUpperCase(c));
                cap = false;
            } else {
                sb.append(c);
            }
        }
        return sb.toString();
    }

    private static String keyLabel(KeyMapping[] slots, int idx) {
        try {
            String s = slots[idx].getKey().getDisplayName().getString();
            if (s == null || s.isEmpty()) return String.valueOf((idx % BAR_SLOTS) + 1);
            // Strip "Key." prefixes from some keyboards
            if (s.startsWith("key.keyboard.")) s = s.substring("key.keyboard.".length());
            if (s.length() > 3) s = s.substring(0, 3);
            return s.toUpperCase(Locale.ROOT);
        } catch (Exception e) {
            return String.valueOf((idx % BAR_SLOTS) + 1);
        }
    }

    private static float interpolateCd(int slot, String id, int ticks) {
        long now = System.currentTimeMillis();
        String safe = id == null ? "" : id;
        if (!safe.equals(CD_LAST_ID[slot]) || ticks != CD_LAST_TICKS[slot]) {
            CD_LAST_ID[slot] = safe;
            CD_LAST_TICKS[slot] = ticks;
            CD_LAST_MS[slot] = now;
        }
        if (ticks <= 0) return 0f;
        float elapsed = (now - CD_LAST_MS[slot]) / 1000f;
        return Math.max(0f, ticks / 20f - elapsed);
    }

    private static void fillRounded(GuiGraphics g, int x, int y, int w, int h, int color) {
        g.fill(x + 2, y, x + w - 2, y + h, color);
        g.fill(x, y + 2, x + w, y + h - 2, color);
        g.fill(x + 1, y + 1, x + w - 1, y + h - 1, color);
    }

    /** Flat filled rect. */
    private static void drawBox(GuiGraphics g, int x, int y, int w, int h, int color) {
        if (XenoHudConfig.legacyTechniqueRenderer) {
            g.fill(x, y, x + w, y + h, color);
        } else {
            SLOT_WIDGET.drawBackground(g, x, y, w, h, color);
        }
    }

    /** Thin border. */
    private static void drawOutlineBox(GuiGraphics g, int x, int y, int w, int h, int color, int thickness) {
        if (XenoHudConfig.legacyTechniqueRenderer) {
            g.renderOutline(x, y, w, h, color);
        } else {
            SLOT_WIDGET.drawOutline(g, x, y, w, h, color, thickness);
        }
    }

    /** Opaque key-badge backdrop. */
    private static void drawBadgeBox(GuiGraphics g, int x, int y, int w, int h) {
        if (XenoHudConfig.legacyTechniqueRenderer) {
            g.fill(x, y, x + w, y + h, 0xEE000000);
        } else {
            SLOT_WIDGET.drawBadgeBackground(g, x, y, w, h);
        }
    }
}
