/**
 * Feature packages for XenoPixels.
 *
 * <h2>Honest status</h2>
 * Much of this tree was bulk-generated by a previous AI as "Xenoverse systems".
 * Most managers under {@code skilltree}, {@code customization}, {@code combo},
 * {@code time}, {@code teaching}, {@code bosschallenge}, {@code twinart},
 * {@code dojo}, {@code moveeffects} are <b>in-memory stubs</b> — not hooked to
 * DragonMineZ, no world content, no player UI. Flags default <b>OFF</b> in
 * {@code xenopixelsmod-features.json}.
 *
 * <p>What is actually LIVE for this DMZ addon lives primarily outside pure stubs:
 * <ul>
 *   <li>{@code dmz.DmzContentBootstrap} — real custom forms into DragonMineZ</li>
 *   <li>{@code client.combat} + {@code network.Bt3CombatPacket} — BT3 combat</li>
 *   <li>{@code client.Xeno*Overlay} — HUD suite</li>
 *   <li>{@code event.KiOverchargeHandler} — KI scaling</li>
 *   <li>{@code transformation.XenoFormRegistry} — menu catalog of those forms</li>
 * </ul>
 *
 * @see net.bullettrain.xenopixelsmod.features.FeatureStatus
 */
package net.bullettrain.xenopixelsmod.features;
