package net.bullettrain.xenopixelsmod.combat.anim;

import net.bullettrain.xenopixelsmod.combat.DmzAnimHelper;

import java.util.Collections;
import java.util.EnumMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;

/**
 * Which DragonMineZ animation each combat beat plays, in each authored generation.
 *
 * <p><b>Common, not client.</b> This used to live inside {@code Bt3AnimationBinding} in a client
 * package, which meant the server had no way to name the clip an NPC should play. The PAL clip id
 * and the mash speed calculation stay over there; the names and lengths live here so both sides can
 * read them.
 *
 * <h2>Four generations, all shipped</h2>
 * <ul>
 *   <li><b>1</b> — exactly what shipped before v3 existed: a mix of our first clips and stock
 *       DragonMineZ ones where theirs already read better.</li>
 *   <li><b>2</b> — the {@code _v2} variants. Not really a second authoring pass: they were derived
 *       from the first by scaling the yaw down.</li>
 *   <li><b>3</b> — the {@code _v3} set, posed from scratch for Budokai Tenkaichi 3 and, crucially,
 *       authored at the length of one mash beat. Generation 1 and 2 clips are 0.40–0.72s against a
 *       0.30s beat, so the mash has to run them at up to 2.4× and the 360s smear; every v3 clip
 *       fits inside about 1.5×.</li>
 *   <li><b>4</b> — forward-centred strikes that preserve DMZ camera/crosshair aim, plus explicit
 *       full-turn spin attacks for the beats that are meant to rotate the fighter.</li>
 * </ul>
 * A generation with no variant for a beat falls back to generation 1 rather than to nothing, which
 * is why older generations may still reuse DragonMineZ clips for beats they did not author.
 *
 * <p>Clip lengths are the {@code animation_length} of the named clip. Ours come from
 * {@code assets/xenopixelsmod/animations/entity/bt3_combat.animation.json} (generated by
 * {@code tools/make_bt3_animations.py}); the DragonMineZ ones from
 * {@code assets/dragonminez/animations/entity/races/combat.animation.json} inside their jar, so a
 * DragonMineZ update that retimes a clip is something to re-read here.
 */
public final class Bt3AnimationCatalog {

    public static final int GEN_MIN = 1;
    public static final int GEN_MAX = 4;
    /** The generation that ships. */
    public static final int GEN_DEFAULT = 4;

    /** One animation: the name DragonMineZ knows it by, and how long it is. */
    public record Clip(String name, float seconds) {
    }

    private record Entry(Clip gen1, Clip gen2, Clip gen3, float speed) {
        Clip forGeneration(int generation) {
            return switch (generation) {
                case 2 -> gen2 != null ? gen2 : gen1;
                case 3 -> gen3 != null ? gen3 : gen1;
                default -> gen1;
            };
        }
    }

    private static final Map<Bt3AnimationIntent, Entry> ENTRIES =
            new EnumMap<>(Bt3AnimationIntent.class);
    private static final Map<Bt3AnimationIntent, Clip> GEN4 =
            new EnumMap<>(Bt3AnimationIntent.class);

    /** Every name this mod ships, for the resolver mixin to whitelist. Insertion-ordered. */
    private static final Set<String> CUSTOM_NAMES = new LinkedHashSet<>();

    static {
        // Keep every authored generation distinct: unsuffixed is v1, then _v2 and _v3.
        xeno(Bt3AnimationIntent.JAB_LEFT, 1.0f,
                "jab_left", 0.28f, "jab_left_v2", 0.24f, "jab_left_v3", 0.24f);
        xeno(Bt3AnimationIntent.JAB_RIGHT, 1.0f,
                "jab_right", 0.28f, "jab_right_v2", 0.24f, "jab_right_v3", 0.24f);

        // Cross V1/V2 are Xeno-owned exact copies of DMZ's left/right one-handed punches.
        // V3 remains the authored BT3 cross, while V4 is the forward-centred custom variant.
        xeno(Bt3AnimationIntent.CROSS_LEFT, 1.05f,
                "cross_left", 0.5f, "cross_left_v2", 0.5f, "cross_left_v3", 0.28f);
        xeno(Bt3AnimationIntent.CROSS_RIGHT, 1.05f,
                "cross_right", 0.5f, "cross_right_v2", 0.5f, "cross_right_v3", 0.28f);
        entry(Bt3AnimationIntent.UPPERCUT_LEFT, 1.0f,
                clip(DmzAnimHelper.UPPERCUT_LEFT, 0.5f), null, xenoClip("uppercut_left_v3", 0.30f));
        entry(Bt3AnimationIntent.UPPERCUT_RIGHT, 1.0f,
                clip(DmzAnimHelper.UPPERCUT_RIGHT, 0.5f), null, xenoClip("uppercut_right_v3", 0.30f));

        xeno(Bt3AnimationIntent.BODY_PUNCH_LEFT, 1.0f,
                "body_punch_left", 0.4f, "body_punch_left_v2", 0.4f, "body_punch_left_v3", 0.28f);
        xeno(Bt3AnimationIntent.BODY_PUNCH_RIGHT, 1.0f,
                "body_punch_right", 0.4f, "body_punch_right_v2", 0.4f, "body_punch_right_v3", 0.28f);
        xeno(Bt3AnimationIntent.HOOK_LEFT, 1.0f,
                "hook_left", 0.42f, "hook_left_v2", 0.42f, "hook_left_v3", 0.30f);
        xeno(Bt3AnimationIntent.HOOK_RIGHT, 1.0f,
                "hook_right", 0.42f, "hook_right_v2", 0.42f, "hook_right_v3", 0.30f);

        // DragonMineZ's low and gut kicks read well and no v3 was authored for them: the mash route
        // only reaches these through the periodic launch kick.
        entry(Bt3AnimationIntent.LOW_KICK_LEFT, 1.1f, clip(DmzAnimHelper.KICK_LOW_L, 0.4167f), null, null);
        entry(Bt3AnimationIntent.LOW_KICK_RIGHT, 1.1f, clip(DmzAnimHelper.KICK_LOW_R, 0.4167f), null, null);
        entry(Bt3AnimationIntent.MID_KICK_LEFT, 1.05f, clip(DmzAnimHelper.KICK_GUT_L, 0.4167f), null, null);
        entry(Bt3AnimationIntent.MID_KICK_RIGHT, 1.05f, clip(DmzAnimHelper.KICK_GUT_R, 0.4167f), null, null);

        xeno(Bt3AnimationIntent.HIGH_ROUNDHOUSE, 1.0f,
                "high_roundhouse", 0.46f, "high_roundhouse_v2", 0.46f, "high_roundhouse_v3", 0.34f);
        xeno(Bt3AnimationIntent.SPINNING_BACK_KICK, 1.0f,
                "spinning_back_kick", 0.54f, "spinning_back_kick_v2", 0.54f, "spinning_back_kick_v3", 0.38f);
        xeno(Bt3AnimationIntent.KNEE_LEFT, 1.0f,
                "knee_left", 0.32f, "knee_left_v2", 0.32f, "knee_left_v3", 0.26f);
        xeno(Bt3AnimationIntent.KNEE_RIGHT, 1.0f,
                "knee_right", 0.32f, "knee_right_v2", 0.32f, "knee_right_v3", 0.26f);

        xeno(Bt3AnimationIntent.STEP_IN_DASH, 1.0f,
                "step_in_dash", 0.28f, "step_in_dash_v2", 0.28f, "step_in_dash_v3", 0.22f);
        xeno(Bt3AnimationIntent.RUSH_IN_CHASE, 1.0f,
                "rush_in_chase", 0.34f, "rush_in_chase_v2", 0.34f, "rush_in_chase_v3", 0.26f);
        xeno(Bt3AnimationIntent.FLYING_KICK, 1.0f,
                "flying_kick", 0.48f, "flying_kick_v2", 0.48f, "flying_kick_v3", 0.36f);
        xeno(Bt3AnimationIntent.HEAVY_FINISH, 1.0f,
                "heavy_finish", 0.7f, "heavy_finish_v2", 0.7f, "heavy_finish_v3", 0.42f);

        xeno(Bt3AnimationIntent.SPIN_HOOK_LEFT, 1.0f,
                "spin_hook_left", 0.7f, "spin_hook_left_v2", 0.7f, "spin_hook_left_v3", 0.44f);
        xeno(Bt3AnimationIntent.SPIN_HOOK_RIGHT, 1.0f,
                "spin_hook_right", 0.7f, "spin_hook_right_v2", 0.7f, "spin_hook_right_v3", 0.44f);
        xeno(Bt3AnimationIntent.SPIN_UPPERCUT_LEFT, 1.0f,
                "spin_uppercut_left", 0.7f, "spin_uppercut_left_v2", 0.7f, "spin_uppercut_left_v3", 0.44f);
        xeno(Bt3AnimationIntent.SPIN_KICK_RIGHT, 1.0f,
                "spin_kick_right", 0.72f, "spin_kick_right_v2", 0.72f, "spin_kick_right_v3", 0.44f);

        v4(Bt3AnimationIntent.STEP_IN_DASH, "step_in_dash", 0.24f);
        v4(Bt3AnimationIntent.JAB_LEFT, "dmz_punch_left", 0.50f);
        v4(Bt3AnimationIntent.JAB_RIGHT, "dmz_punch_right", 0.50f);
        v4(Bt3AnimationIntent.CROSS_LEFT, "cross_left", 0.28f);
        v4(Bt3AnimationIntent.CROSS_RIGHT, "cross_right", 0.28f);
        v4(Bt3AnimationIntent.BODY_PUNCH_LEFT, "body_punch_left", 0.28f);
        v4(Bt3AnimationIntent.BODY_PUNCH_RIGHT, "body_punch_right", 0.28f);
        v4(Bt3AnimationIntent.HOOK_LEFT, "hook_left", 0.30f);
        v4(Bt3AnimationIntent.HOOK_RIGHT, "hook_right", 0.30f);
        v4(Bt3AnimationIntent.UPPERCUT_LEFT, "uppercut_left", 0.30f);
        v4(Bt3AnimationIntent.UPPERCUT_RIGHT, "uppercut_right", 0.30f);
        v4(Bt3AnimationIntent.LOW_KICK_LEFT, "low_kick_left", 0.32f);
        v4(Bt3AnimationIntent.LOW_KICK_RIGHT, "low_kick_right", 0.32f);
        v4(Bt3AnimationIntent.MID_KICK_LEFT, "mid_kick_left", 0.34f);
        v4(Bt3AnimationIntent.MID_KICK_RIGHT, "mid_kick_right", 0.34f);
        v4(Bt3AnimationIntent.HIGH_ROUNDHOUSE, "high_roundhouse", 0.40f);
        v4(Bt3AnimationIntent.SPINNING_BACK_KICK, "spinning_back_kick", 0.52f);
        v4(Bt3AnimationIntent.KNEE_LEFT, "knee_left", 0.28f);
        v4(Bt3AnimationIntent.KNEE_RIGHT, "knee_right", 0.28f);
        v4(Bt3AnimationIntent.FLYING_KICK, "flying_kick", 0.38f);
        v4(Bt3AnimationIntent.RUSH_IN_CHASE, "rush_in_chase", 0.28f);
        v4(Bt3AnimationIntent.HEAVY_FINISH, "heavy_finish", 0.42f);
        v4(Bt3AnimationIntent.SPIN_HOOK_LEFT, "spin_hook_left", 0.52f);
        v4(Bt3AnimationIntent.SPIN_HOOK_RIGHT, "spin_hook_right", 0.52f);
        v4(Bt3AnimationIntent.SPIN_UPPERCUT_LEFT, "spin_uppercut_left", 0.52f);
        v4(Bt3AnimationIntent.SPIN_KICK_RIGHT, "spin_kick_right", 0.54f);

        // Not bound to an intent, but shipped and therefore whitelisted.
        register(DmzAnimHelper.HAKAI_HOLD, DmzAnimHelper.HAKAI_FIRE);
    }

    private Bt3AnimationCatalog() {
    }

    /** Clamps anything to a generation this build knows. */
    public static int clampGeneration(int generation) {
        return Math.max(GEN_MIN, Math.min(GEN_MAX, generation));
    }

    /** The clip {@code intent} plays in {@code generation}, or null for an unbound intent. */
    public static Clip clipFor(Bt3AnimationIntent intent, int generation) {
        Entry entry = intent == null ? null : ENTRIES.get(intent);
        if (entry == null) {
            return null;
        }
        int clamped = clampGeneration(generation);
        if (clamped == 4) {
            return GEN4.getOrDefault(intent, entry.forGeneration(3));
        }
        return entry.forGeneration(clamped);
    }

    /** The authored playback multiplier for {@code intent}, before any beat scaling. */
    public static float speedOf(Bt3AnimationIntent intent) {
        Entry entry = intent == null ? null : ENTRIES.get(intent);
        return entry == null ? 1.0f : entry.speed();
    }

    /**
     * Every animation name this mod ships, which DragonMineZ's {@code CombatAnimationResolver} must
     * be told about or it resolves them to nothing.
     */
    public static Set<String> customAnimationNames() {
        return Collections.unmodifiableSet(CUSTOM_NAMES);
    }

    /**
     * Every name that may be played through the scripting API: ours plus the stock DragonMineZ
     * clips the table above binds. Anything outside this is rejected so a script gets an answer
     * rather than silence.
     */
    public static Set<String> playableAnimationNames() {
        Set<String> all = new LinkedHashSet<>(CUSTOM_NAMES);
        for (Bt3AnimationIntent intent : ENTRIES.keySet()) {
            for (int gen = GEN_MIN; gen <= GEN_MAX; gen++) {
                all.add(clipFor(intent, gen).name());
            }
        }
        return Collections.unmodifiableSet(all);
    }

    public static boolean isPlayable(String animation) {
        return animation != null && playableAnimationNames().contains(animation.trim());
    }

    private static Clip clip(String name, float seconds) {
        register(name);
        return new Clip(name, seconds);
    }

    private static Clip xenoClip(String suffix, float seconds) {
        return clip("combat.xeno_" + suffix, seconds);
    }

    private static void xeno(Bt3AnimationIntent intent, float speed,
                             String g1, float s1, String g2, float s2, String g3, float s3) {
        entry(intent, speed, xenoClip(g1, s1), xenoClip(g2, s2), xenoClip(g3, s3));
    }

    private static void entry(Bt3AnimationIntent intent, float speed, Clip g1, Clip g2, Clip g3) {
        ENTRIES.put(intent, new Entry(g1, g2, g3, speed));
    }

    private static void v4(Bt3AnimationIntent intent, String suffix, float seconds) {
        GEN4.put(intent, xenoClip(suffix + "_v4", seconds));
    }

    private static void register(String... names) {
        for (String name : names) {
            if (name != null && name.startsWith("combat.xeno_")) {
                CUSTOM_NAMES.add(name);
            }
        }
    }
}
