package net.bullettrain.xenopixelsmod.client.hud;

import net.minecraft.resources.ResourceLocation;

/** Generated by {@code tools/gen_dmz_neon_atlas.py}; do not edit. */
public final class XenoNeonAtlas {
    public static final ResourceLocation TEXTURE = ResourceLocation.fromNamespaceAndPath(
            "xenopixelsmod", "textures/gui/xeno_neon_character.png");
    public static final int ATLAS_WIDTH = 2048;
    public static final int ATLAS_HEIGHT = 2048;
    public record Sprite(int u, int v, int sourceWidth, int sourceHeight, int width, int height) {}

    public static final Sprite BASIC_ROW = new Sprite(1050, 920, 450, 55, 90, 11);
    public static final Sprite DIVIDER = new Sprite(1690, 920, 350, 40, 70, 8);
    public static final Sprite INFO_HEADER = new Sprite(0, 770, 480, 145, 96, 29);
    public static final Sprite INFO_PANEL = new Sprite(0, 0, 510, 765, 102, 153);
    public static final Sprite INFO_STATS_HEADER = new Sprite(1220, 770, 405, 70, 81, 14);
    public static final Sprite MULTIPLIER_FIELD = new Sprite(1505, 920, 130, 55, 26, 11);
    public static final Sprite NAMEPLATE = new Sprite(1355, 0, 620, 160, 124, 32);
    public static final Sprite NAV_BASE = new Sprite(485, 770, 125, 125, 25, 25);
    public static final Sprite ORB_BLUE = new Sprite(1055, 770, 50, 90, 10, 18);
    public static final Sprite ORB_GOLD = new Sprite(1110, 770, 50, 90, 10, 18);
    public static final Sprite ORB_RED = new Sprite(1165, 770, 50, 90, 10, 18);
    public static final Sprite PLUS = new Sprite(1640, 920, 45, 45, 9, 9);
    public static final Sprite SCAN_RING = new Sprite(1030, 0, 320, 320, 64, 64);
    public static final Sprite STATISTICS_HEADER = new Sprite(615, 770, 435, 115, 87, 23);
    public static final Sprite STATISTIC_ROW = new Sprite(0, 920, 520, 65, 104, 13);
    public static final Sprite STATS_PANEL = new Sprite(515, 0, 510, 750, 102, 150);
    public static final Sprite STAT_ROW = new Sprite(525, 920, 520, 65, 104, 13);

    public static final int[][] INFO_ROWS = {{34, 11}, {45, 11}, {56, 11}, {67, 11}};

    public static final int[][] STAT_ROWS = {{74, 11}, {85, 11}, {96, 11}, {107, 11}, {118, 11}, {129, 11}, {140, 11}};

    public static final int[][] STATISTIC_ROWS = {{29, 11}, {41, 11}, {53, 11}, {65, 11}, {77, 11}, {89, 11}, {101, 11}};

    public static final int[][] SUMMARY_ROWS = {{113, 11}, {125, 11}, {137, 11}};

    public static final int INFO_LABEL_X = 9;
    public static final int INFO_VALUE_X = 57;
    public static final int INFO_RIGHT_X = 96;
    public static final int STAT_LABEL_X = 13;
    public static final int STAT_RIGHT_X = 99;
    public static final int PLUS_X = 2;
    public static final int PLUS_Y = 2;
    public static final int PLUS_WIDTH = 9;
    public static final int PLUS_HEIGHT = 9;
    public static final int STATISTIC_LABEL_X = 8;
    public static final int STATISTIC_RIGHT_X = 97;
    public static final int SUMMARY_LABEL_X = 8;
    public static final int SUMMARY_RIGHT_X = 97;

    public static final int LABEL = 0xFFE9F8FF;
    public static final int VALUE = 0xFFFFFFFF;
    public static final int HEADER = 0xFF7CEBFF;
    public static final int GOLD = 0xFFFFC85A;
    public static final int RED = 0xFFFF5E70;
    public static final int GREEN = 0xFF72FF98;
    public static final int MAGENTA = 0xFFFF72DE;
    public static final int CYAN = 0xFF55EFFF;
    public static final int ORANGE = 0xFFFF9B52;

    private XenoNeonAtlas() {}
}
