package net.bullettrain.xenopixelsmod.client.hud;

import net.minecraft.resources.ResourceLocation;

/**
 * Sprite rectangles for the BT3 HUD atlas.
 *
 * <p><b>Generated by {@code tools/gen_bt3_hud_atlas.py} -- do not edit.</b> The atlas PNG,
 * its manifest and this file all come out of one pass, so a sprite cannot move within the
 * atlas without its rectangle moving with it. A hand-edited rectangle renders a
 * neighbouring sprite rather than failing, which is exactly why this is generated.
 *
 * <p>Re-run the generator after changing the source art or the sprite selection.
 */
public final class XenoBt3HudAtlas {

    public static final ResourceLocation TEXTURE =
            ResourceLocation.fromNamespaceAndPath(
                    "xenopixelsmod", "textures/gui/xeno_bt3_hud_atlas.png");

    public static final int ATLAS_WIDTH = 256;
    public static final int ATLAS_HEIGHT = 256;

    /** One sprite's position and size within {@link #TEXTURE}. */
    public record Sprite(int u, int v, int width, int height) {}

    public static final Sprite ENERGY_STREAK = new Sprite(207, 0, 21, 35);
    public static final Sprite HP_BAR = new Sprite(90, 96, 122, 19);
    public static final Sprite KI_BAR = new Sprite(0, 122, 120, 19);
    public static final Sprite NAMEPLATE = new Sprite(0, 60, 186, 35);
    public static final Sprite PORTRAIT_RING = new Sprite(0, 0, 62, 59);
    public static final Sprite PROMPT_ARROW = new Sprite(187, 60, 29, 35);
    public static final Sprite PROMPT_PLATE = new Sprite(0, 96, 89, 25);
    public static final Sprite STAMINA_BAR = new Sprite(121, 122, 113, 19);
    public static final Sprite TECHNIQUE_BLUE = new Sprite(135, 0, 35, 37);
    public static final Sprite TECHNIQUE_GREEN = new Sprite(171, 0, 35, 36);
    public static final Sprite TECHNIQUE_ORANGE = new Sprite(98, 0, 36, 38);
    public static final Sprite TECHNIQUE_PURPLE = new Sprite(63, 0, 34, 39);

    private XenoBt3HudAtlas() {
    }
}
