package net.bullettrain.xenopixelsmod.client.hud;

import net.minecraft.resources.ResourceLocation;

/**
 * Sprite rectangles, row anchors and palette for the neon DragonMineZ character screen.
 *
 * <p><b>Generated by {@code tools/gen_dmz_neon_atlas.py} -- do not edit.</b> Sprites are
 * stored at 5x logical density; draw size and source size stay separate so Minecraft
 * samples the supplied artwork instead of magnifying a pre-shrunk copy.
 *
 * <p>The panels are single slabs with their rows drawn into the art, so the row bands below
 * are the interiors: {@code {y, height}} in logical pixels, relative to the slab's own
 * top-left corner. They were measured off the art by the generator, not chosen.
 */
public final class XenoNeonAtlas {

    public static final ResourceLocation TEXTURE =
            ResourceLocation.fromNamespaceAndPath(
                    "xenopixelsmod", "textures/gui/xeno_neon_character.png");

    public static final int ATLAS_WIDTH = 2048;
    public static final int ATLAS_HEIGHT = 2048;

    /** One sprite's atlas rectangle and logical on-screen size. */
    public record Sprite(int u, int v, int sourceWidth, int sourceHeight,
                         int width, int height) {}

    public static final Sprite INFO_PANEL = new Sprite(0, 0, 505, 790, 101, 158);
    public static final Sprite NAMEPLATE = new Sprite(0, 795, 620, 150, 124, 30);
    public static final Sprite NAV_CHARACTER = new Sprite(625, 795, 130, 150, 26, 30);
    public static final Sprite NAV_ITEMS = new Sprite(760, 795, 125, 150, 25, 30);
    public static final Sprite NAV_PARTY = new Sprite(890, 795, 125, 150, 25, 30);
    public static final Sprite NAV_QUESTS = new Sprite(1020, 795, 125, 150, 25, 30);
    public static final Sprite NAV_SETTINGS = new Sprite(1150, 795, 125, 150, 25, 30);
    public static final Sprite NAV_SKILLS = new Sprite(1280, 795, 125, 150, 25, 30);
    public static final Sprite ORB_BLUE = new Sprite(1410, 795, 95, 85, 19, 17);
    public static final Sprite ORB_GOLD = new Sprite(1510, 795, 95, 85, 19, 17);
    public static final Sprite ORB_RED = new Sprite(1610, 795, 100, 85, 20, 17);
    public static final Sprite SCAN_RING = new Sprite(1030, 0, 410, 380, 82, 76);
    public static final Sprite STATS_PANEL = new Sprite(510, 0, 515, 660, 103, 132);

    /** Level, TPs, Form, Class and the assignable-points row. */
    public static final int[][] INFO_ROWS = {
            {28, 8},
            {36, 7},
            {44, 7},
            {51, 7},
            {59, 4}};

    /** The seven spendable-stat shells, top to bottom. */
    public static final int[][] STAT_ROWS = {
            {78, 7},
            {87, 8},
            {97, 8},
            {106, 8},
            {116, 8},
            {125, 8},
            {135, 8}};

    /** The seven derived-statistic rows on the right slab. */
    public static final int[][] STATISTIC_ROWS = {
            {26, 8},
            {35, 8},
            {43, 8},
            {51, 8},
            {59, 8},
            {67, 8},
            {75, 8}};

    /** The three-row summary box lower in the right slab. */
    public static final int[][] SUMMARY_ROWS = {
            {101, 8},
            {109, 7},
            {116, 8}};

    /** Text insets inside the left slab, logical pixels from its left edge. */
    public static final int INFO_LABEL_X = 10;
    public static final int INFO_VALUE_X = 42;
    public static final int INFO_RIGHT_X = 93;
    public static final int STAT_LABEL_X = 26;
    public static final int STAT_RIGHT_X = 94;

    /** The plus button's rectangle, relative to the top-left of its stat row band. */
    public static final int PLUS_X = 14;
    public static final int PLUS_Y = 1;
    public static final int PLUS_WIDTH = 9;
    public static final int PLUS_HEIGHT = 6;

    /** Text insets inside the right slab. */
    public static final int STATISTIC_LABEL_X = 12;
    public static final int STATISTIC_RIGHT_X = 94;
    public static final int SUMMARY_LABEL_X = 15;
    public static final int SUMMARY_RIGHT_X = 91;

    /**
     * The palette, sampled from {@code example/current_example_full_hud.png} at the
     * coordinates recorded in the generator. These are the reference render's own colours,
     * not an approximation of them.
     */
    public static final int CYAN = 0xFF0093CC;
    public static final int GOLD = 0xFFFFE005;
    public static final int GREEN = 0xFF00C569;
    public static final int HEADER = 0xFFFFEC13;
    public static final int LABEL = 0xFFC3F8FC;
    public static final int MAGENTA = 0xFFEA62FF;
    public static final int ORANGE = 0xFFFF7E18;
    public static final int RED = 0xFFFF3A4A;
    public static final int VALUE = 0xFFFFFFFF;

    private XenoNeonAtlas() {
    }
}
