package net.bullettrain.xenopixelsmod.client.hud;

import net.minecraft.resources.ResourceLocation;

/**
 * Sprite rectangles for the rebuilt DragonMineZ character screen.
 *
 * <p><b>Generated by {@code tools/gen_dmz_hd_atlas.py} -- do not edit.</b> Sprites are
 * stored at 4x logical density. Draw size and source size stay separate so Minecraft
 * samples the supplied HD artwork instead of magnifying a pre-shrunk copy.
 */
public final class XenoDmzHdAtlas {

    public static final ResourceLocation TEXTURE =
            ResourceLocation.fromNamespaceAndPath(
                    "xenopixelsmod", "textures/gui/xeno_dmz_hd_atlas.png");

    public static final int ATLAS_WIDTH = 2048;
    public static final int ATLAS_HEIGHT = 2048;

    /** One sprite's atlas rectangle and logical on-screen size. */
    public record Sprite(int u, int v, int sourceWidth, int sourceHeight,
                         int width, int height) {}

    public static final Sprite ACCENT = new Sprite(1208, 0, 8, 240, 2, 60);
    public static final Sprite BOTTOM_BOX = new Sprite(1220, 0, 520, 204, 130, 51);
    public static final Sprite DIVIDER = new Sprite(0, 1116, 520, 12, 130, 3);
    public static final Sprite INFO_DIVIDER = new Sprite(524, 1116, 520, 8, 130, 2);
    public static final Sprite INFO_HEADER = new Sprite(876, 856, 480, 100, 120, 25);
    public static final Sprite INFO_PANEL = new Sprite(604, 0, 600, 824, 150, 206);
    public static final Sprite KANJI_CIRCLE = new Sprite(940, 1020, 72, 72, 18, 18);
    public static final Sprite NAMEPLATE = new Sprite(0, 856, 872, 160, 218, 40);
    public static final Sprite NAV_CHARACTER = new Sprite(388, 1020, 88, 88, 22, 22);
    public static final Sprite NAV_ITEMS = new Sprite(480, 1020, 88, 88, 22, 22);
    public static final Sprite NAV_PARTY = new Sprite(572, 1020, 88, 88, 22, 22);
    public static final Sprite NAV_QUESTS = new Sprite(664, 1020, 88, 88, 22, 22);
    public static final Sprite NAV_SETTINGS = new Sprite(756, 1020, 88, 88, 22, 22);
    public static final Sprite NAV_SKILLS = new Sprite(848, 1020, 88, 88, 22, 22);
    public static final Sprite ORB_BLUE = new Sprite(1616, 1020, 48, 48, 12, 12);
    public static final Sprite ORB_RED = new Sprite(1668, 1020, 48, 48, 12, 12);
    public static final Sprite ORB_YELLOW = new Sprite(1720, 1020, 48, 48, 12, 12);
    public static final Sprite PLUS_BUTTON = new Sprite(1772, 1020, 44, 44, 11, 11);
    public static final Sprite ROW_DIVIDER = new Sprite(1048, 1116, 520, 8, 130, 2);
    public static final Sprite STATS_BARS_ICON = new Sprite(1016, 1020, 72, 72, 18, 18);
    public static final Sprite STATS_HEADER = new Sprite(1360, 856, 480, 100, 120, 25);
    public static final Sprite STATS_PANEL = new Sprite(0, 0, 600, 852, 150, 213);
    public static final Sprite STATS_SUBHEADER = new Sprite(0, 1020, 384, 92, 96, 23);
    public static final Sprite STAT_ROW = new Sprite(1092, 1020, 520, 72, 130, 18);

    private XenoDmzHdAtlas() {
    }
}
