package net.bullettrain.xenopixelsmod.client.hud;

import net.minecraft.resources.ResourceLocation;

/**
 * Sprite rectangles for the XenoPixels DragonMineZ stats screen.
 *
 * <p><b>Generated by {@code tools/gen_bt3_menu_atlas.py} -- do not edit.</b> Every sprite is
 * stored at the size the screen draws it, so every blit is 1:1 and nothing is resampled
 * while rendering.
 */
public final class XenoBt3MenuAtlas {

    public static final ResourceLocation TEXTURE =
            ResourceLocation.fromNamespaceAndPath(
                    "xenopixelsmod", "textures/gui/xeno_bt3_menu_atlas.png");

    public static final int ATLAS_WIDTH = 512;
    public static final int ATLAS_HEIGHT = 256;

    /** One sprite's position and size within {@link #TEXTURE}. */
    public record Sprite(int u, int v, int width, int height) {}

    public static final Sprite BUTTON_CHARACTER = new Sprite(393, 0, 22, 22);
    public static final Sprite BUTTON_ITEMS = new Sprite(416, 0, 22, 22);
    public static final Sprite BUTTON_PARTY = new Sprite(439, 0, 22, 22);
    public static final Sprite BUTTON_QUESTS = new Sprite(462, 0, 22, 22);
    public static final Sprite BUTTON_SETTINGS = new Sprite(485, 0, 22, 22);
    public static final Sprite BUTTON_SKILLS = new Sprite(0, 181, 22, 22);
    public static final Sprite INFO_PANEL = new Sprite(0, 0, 120, 180);
    public static final Sprite NAMEPLATE = new Sprite(242, 0, 150, 50);
    public static final Sprite ORB_ICONS = new Sprite(23, 181, 60, 20);
    public static final Sprite STATS_PANEL = new Sprite(121, 0, 120, 180);

    private XenoBt3MenuAtlas() {
    }
}
