package net.bullettrain.xenopixelsmod.client.npc;

import net.bullettrain.xenopixelsmod.client.ui.atlas.AtlasButton;
import net.bullettrain.xenopixelsmod.client.ui.atlas.AtlasSound;
import net.bullettrain.xenopixelsmod.client.ui.atlas.XenoAtlasSprites;
import net.bullettrain.xenopixelsmod.network.ModNetwork;
import net.bullettrain.xenopixelsmod.network.packet.RequestXenoNpcEditorPacket;
import net.bullettrain.xenopixelsmod.network.packet.XenoNpcDeletePacket;
import net.bullettrain.xenopixelsmod.network.packet.XenoNpcNearbyPackets;
import net.bullettrain.xenopixelsmod.npc.NpcNearbyList;
import net.bullettrain.xenopixelsmod.npc.XenoNpcNearbyService;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

import java.util.ArrayList;
import java.util.List;

/**
 * Nearby NPCs (NPC wand, right-click the air): the CustomNPCs screen 1:1 - title above a 256x216
 * panel, search field and "distance : name" list on the left, 80x20 buttons on the right - drawn in
 * the blue DMZ atlas (mynpcs_nearby_panel / mynpcs_button_80x20, generated by
 * tools/atlas-panels/xeno_extra_specs.py). Every action goes to the server, which rechecks
 * permission and range and answers with a fresh list. Placing an NPC is the wand on a block.
 */
public final class XenoNpcNearbyScreen extends Screen {
    private static final String PANEL = "mynpcs_nearby_panel";
    private static final String BUTTON = "mynpcs_button_80x20";
    private static final int W = 256;
    private static final int H = 216;
    private static final int LIST_X = 5;
    private static final int LIST_Y = 26;
    private static final int LIST_W = 163;
    private static final int LIST_H = 185;
    private static final int ROW_H = 14;
    private static final int ROWS = (LIST_H - 4) / ROW_H;
    private static final int BUTTON_X = 171;
    private static final int TEXT = 0xFFE0F0FF;
    private static final int TEXT_DIM = 0xFFB8CEE0;
    private static final int SELECTED = 0xFF55EFFF;
    private static final int FROZEN = 0xFFFFC857;
    private static final int LIST_FILL = 0xE0020A18;
    private static final int LIST_EDGE = 0xFF2E5C8A;
    private static final long CONFIRM_MS = 3000;

    private List<NpcNearbyList.Entry> entries;
    private List<NpcNearbyList.Entry> shown = List.of();
    private int selectedId = -1;
    private int scroll;
    private EditBox search;
    private AtlasButton deleteButton;
    private AtlasButton freezeButton;
    private long deleteArmedUntil;
    private int left;
    private int top;

    public XenoNpcNearbyScreen(List<NpcNearbyList.Entry> entries) {
        super(Component.literal("Nearby NPCs"));
        this.entries = new ArrayList<>(entries);
    }

    /** A fresh list from the server while open; the selection is kept by entity id. */
    public void update(List<NpcNearbyList.Entry> fresh) {
        this.entries = new ArrayList<>(fresh);
        applyFilter();
    }

    @Override
    protected void init() {
        left = (width - W) / 2;
        top = (height - H) / 2;
        String query = search == null ? "" : search.getValue();
        search = new EditBox(font, left + LIST_X, top + 5, LIST_W, 17, Component.literal("Search"));
        search.setValue(query);
        search.setResponder(v -> {
            scroll = 0;
            applyFilter();
        });
        addRenderableWidget(search);

        int bx = left + BUTTON_X;
        int y = top + 5;
        addRenderableWidget(button(bx, y, "Edit", this::edit));
        deleteButton = addRenderableWidget(button(bx, y + 22, "Delete", this::delete));
        addRenderableWidget(button(bx, y + 44, "Reset", () -> act(XenoNpcNearbyService.Action.RESET)));
        addRenderableWidget(button(bx, y + 66, "Tp to", () -> act(XenoNpcNearbyService.Action.TP_TO)));
        addRenderableWidget(button(bx, y + 88, "Bring here", () -> act(XenoNpcNearbyService.Action.BRING)));
        addRenderableWidget(button(bx, y + 118, "Reset All", () -> send(XenoNpcNearbyService.Action.RESET_ALL, -1)));
        freezeButton = addRenderableWidget(button(bx, y + 140, "Freeze Npcs",
                () -> send(XenoNpcNearbyService.Action.FREEZE_TOGGLE, -1)));
        applyFilter();
        refreshLabels();
    }

    private static AtlasButton button(int x, int y, String label, Runnable action) {
        // AtlasButton plays the DMZ click itself.
        return new AtlasButton(x, y, Component.literal(label), BUTTON, b -> action.run());
    }

    @Override
    public void tick() {
        super.tick();
        refreshLabels();
    }

    private void refreshLabels() {
        if (deleteButton != null) {
            deleteButton.setMessage(Component.literal(
                    System.currentTimeMillis() <= deleteArmedUntil ? "Confirm?" : "Delete"));
        }
        if (freezeButton != null) {
            boolean allFrozen = !entries.isEmpty() && entries.stream().allMatch(NpcNearbyList.Entry::frozen);
            freezeButton.setMessage(Component.literal(allFrozen ? "Unfreeze Npcs" : "Freeze Npcs"));
        }
    }

    private void applyFilter() {
        shown = NpcNearbyList.filterSort(entries, search == null ? "" : search.getValue());
        if (shown.stream().noneMatch(e -> e.entityId() == selectedId)) selectedId = -1;
        scroll = Math.max(0, Math.min(scroll, Math.max(0, shown.size() - ROWS)));
    }

    private NpcNearbyList.Entry selected() {
        for (NpcNearbyList.Entry e : shown) if (e.entityId() == selectedId) return e;
        return null;
    }

    private void act(XenoNpcNearbyService.Action action) {
        NpcNearbyList.Entry e = selected();
        if (e != null) send(action, e.entityId());
    }

    private void send(XenoNpcNearbyService.Action action, int entityId) {
        ModNetwork.sendToServer(new XenoNpcNearbyPackets.Action(action, entityId, ""));
    }

    private void edit() {
        NpcNearbyList.Entry e = selected();
        if (e != null) ModNetwork.sendToServer(new RequestXenoNpcEditorPacket(e.entityId()));
    }

    /** Delete asks once: the first click arms it for three seconds, the second deletes. */
    private void delete() {
        NpcNearbyList.Entry e = selected();
        if (e == null) return;
        long now = System.currentTimeMillis();
        if (now > deleteArmedUntil) {
            deleteArmedUntil = now + CONFIRM_MS;
            refreshLabels();
            return;
        }
        deleteArmedUntil = 0;
        ModNetwork.sendToServer(new XenoNpcDeletePacket(e.entityId(), e.revision()));
        ModNetwork.sendToServer(new XenoNpcNearbyPackets.Request());
        refreshLabels();
    }

    // ------------------------------------------------------------------ input

    @Override
    public boolean mouseClicked(double mouseX, double mouseY, int button) {
        int lx = left + LIST_X;
        int ly = top + LIST_Y + 2;
        if (mouseX >= lx && mouseX < lx + LIST_W && mouseY >= ly && mouseY < ly + ROWS * ROW_H) {
            int index = scroll + (int) ((mouseY - ly) / ROW_H);
            if (index < shown.size()) {
                selectedId = shown.get(index).entityId();
                deleteArmedUntil = 0;
                refreshLabels();
                AtlasSound.click();
                return true;
            }
        }
        return super.mouseClicked(mouseX, mouseY, button);
    }

    @Override
    public boolean mouseScrolled(double mouseX, double mouseY, double dx, double dy) {
        scroll = Math.max(0, Math.min(scroll - (int) Math.signum(dy), Math.max(0, shown.size() - ROWS)));
        return true;
    }

    @Override
    public boolean isPauseScreen() {
        return false;
    }

    // ------------------------------------------------------------------ drawing

    @Override
    public void renderBackground(GuiGraphics g, int mouseX, int mouseY, float partialTick) {
        super.renderBackground(g, mouseX, mouseY, partialTick);
        XenoAtlasSprites.blit(g, PANEL, left, top);
        // List well, as CustomNPCs' dark list area.
        int lx = left + LIST_X;
        int ly = top + LIST_Y;
        g.fill(lx, ly, lx + LIST_W, ly + LIST_H, LIST_FILL);
        g.renderOutline(lx - 1, ly - 1, LIST_W + 2, LIST_H + 2, LIST_EDGE);
    }

    @Override
    public void render(GuiGraphics g, int mouseX, int mouseY, float partialTick) {
        super.render(g, mouseX, mouseY, partialTick);
        g.drawCenteredString(font, title, left + W / 2, top - 11, TEXT);
        drawList(g, mouseX, mouseY);
    }

    private void drawList(GuiGraphics g, int mouseX, int mouseY) {
        int lx = left + LIST_X;
        int ly = top + LIST_Y + 2;
        if (shown.isEmpty()) {
            g.drawCenteredString(font, entries.isEmpty() ? "No Xeno NPCs nearby" : "No match",
                    lx + LIST_W / 2, ly + 6, TEXT_DIM);
            return;
        }
        for (int row = 0; row < ROWS && scroll + row < shown.size(); row++) {
            NpcNearbyList.Entry e = shown.get(scroll + row);
            int y = ly + row * ROW_H;
            boolean selectedRow = e.entityId() == selectedId;
            boolean hover = mouseX >= lx && mouseX < lx + LIST_W && mouseY >= y && mouseY < y + ROW_H;
            if (selectedRow || hover) g.fill(lx + 1, y, lx + LIST_W - 1, y + ROW_H, selectedRow ? 0x5055EFFF : 0x2855EFFF);
            int colour = selectedRow ? SELECTED : e.frozen() ? FROZEN : TEXT;
            g.drawString(font, font.plainSubstrByWidth(NpcNearbyList.label(e), LIST_W - 8), lx + 4, y + 3, colour, false);
        }
        if (shown.size() > ROWS) {
            int trackH = ROWS * ROW_H;
            int barH = Math.max(10, trackH * ROWS / shown.size());
            int barY = ly + (trackH - barH) * scroll / Math.max(1, shown.size() - ROWS);
            g.fill(lx + LIST_W - 3, barY, lx + LIST_W - 1, barY + barH, TEXT_DIM);
        }
    }
}
